version: '3'
services:
  app:
    image: ${project}-${env}-${service}:build
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
